import SwiftUI

enum AppTypography {
    static let authScreenTitle = Font.system(size: 30, weight: .bold)
    static let authScreenSubtitle = Font.system(size: 16, weight: .regular)
    static let authBody = Font.system(size: 16, weight: .regular)
    static let authHelperText = Font.system(size: 12, weight: .regular)
    static let authInlineAction = Font.system(size: 14, weight: .semibold)
    static let authPromptBody = Font.system(size: 14, weight: .regular)
    static let authPromptAction = Font.system(size: 17, weight: .semibold)
    static let authLegalCopy = Font.system(size: 12, weight: .regular)
    static let authSectionLabel = Font.system(size: 10, weight: .semibold)
    static let authFeatureTitle = Font.system(size: 14, weight: .bold)
    static let authFeatureCaption = Font.system(size: 10, weight: .regular)
    static let authCardEyebrow = Font.system(size: 9, weight: .semibold)
    static let authCardTitle = Font.system(size: 14, weight: .medium)
    static let authPillLabel = Font.system(size: 12, weight: .semibold)

    static let homeTopBarTitle = Font.system(size: 24, weight: .bold)
    static let homeGreetingLine = Font.system(size: 16, weight: .medium)
    static let homeGreetingHeadline = Font.system(size: 30, weight: .heavy)
    static let homeCardEyebrow = Font.system(size: 10, weight: .bold)
    static let homeCardTitle = Font.system(size: 18, weight: .bold)
    static let homeSectionTitle = Font.system(size: 20, weight: .bold)
    static let homeFeatureTitle = Font.system(size: 24, weight: .bold)
    static let homeHeroTitle = Font.system(size: 36, weight: .black)
    static let homeHeroBody = Font.system(size: 14, weight: .medium)
    static let homeBody = Font.system(size: 16, weight: .bold)
    static let homeCaption = Font.system(size: 12, weight: .bold)
    static let homeMeta = Font.system(size: 10, weight: .bold)
    static let homeMetaRegular = Font.system(size: 10, weight: .regular)
    static let homeMetric = Font.system(size: 30, weight: .black)
    static let homeMetricSmall = Font.system(size: 18, weight: .black)
    static let homeButtonSmall = Font.system(size: 12, weight: .bold)
    static let homeButtonMedium = Font.system(size: 14, weight: .bold)
    static let homeButtonLarge = Font.system(size: 18, weight: .bold)

    static let quickRevisionTitle = Font.system(size: 30, weight: .heavy)
    static let quickRevisionSubtitle = Font.system(size: 16, weight: .regular)
    static let quickRevisionSectionLabel = Font.system(size: 12, weight: .bold)
    static let quickRevisionListTitle = Font.system(size: 16, weight: .bold)
    static let quickRevisionListSubtitle = Font.system(size: 14, weight: .regular)
    static let quickRevisionRecentMeta = Font.system(size: 11, weight: .bold)
    static let quickRevisionRecentTitle = Font.system(size: 14, weight: .semibold)
    static let quickRevisionTopBarTitle = Font.system(size: 24, weight: .bold)
    static let quickRevisionTopicTitle = Font.system(size: 36, weight: .heavy)
    static let quickRevisionTopicSubtitle = Font.system(size: 16, weight: .medium)
    static let quickRevisionTopicRowSubtitle = Font.system(size: 12, weight: .regular)
    static let quickRevisionContentSubtitle = Font.system(size: 16, weight: .semibold)
    static let quickRevisionDefinitionTitle = Font.system(size: 14, weight: .bold)
    static let quickRevisionCardBody = Font.system(size: 14, weight: .regular)
    static let quickRevisionFormulaLabel = Font.system(size: 12, weight: .bold)
    static let quickRevisionFormulaExpression = Font.system(size: 22, weight: .heavy)
    static let quickRevisionLawTitle = Font.system(size: 14, weight: .bold)
    static let quickRevisionSummaryBody = Font.system(size: 14, weight: .medium)

    static let recallToolsTopBarTitle = Font.system(size: 24, weight: .bold)
    static let recallToolsEyebrow = Font.system(size: 11, weight: .bold)
    static let recallToolsTitle = Font.system(size: 30, weight: .heavy)
    static let recallToolsSubtitle = Font.system(size: 18, weight: .regular)
    static let recallToolsCardTitle = Font.system(size: 18, weight: .bold)
    static let recallToolsCardBody = Font.system(size: 14, weight: .regular)
    static let recallToolsMetadata = Font.system(size: 10, weight: .bold)
    static let recallToolsSectionTitle = Font.system(size: 16, weight: .bold)
    static let recallToolsRecentTitle = Font.system(size: 14, weight: .bold)
    static let recallToolsRecentDetail = Font.system(size: 12, weight: .regular)

    static let flashcardsTopicSelectionTitle = Font.system(size: 30, weight: .heavy)
    static let flashcardsTopicSelectionSubtitle = Font.system(size: 18, weight: .regular)
    static let flashcardsTopicSelectionSectionLabel = Font.system(size: 12, weight: .bold)
    static let flashcardsTopicSelectionRowTitle = Font.system(size: 18, weight: .bold)
    static let flashcardsTopicSelectionRowDetail = Font.system(size: 16, weight: .regular)
    static let flashcardsTopicSelectionRecentTitle = Font.system(size: 14, weight: .bold)
    static let flashcardsTopicSelectionRecentDetail = Font.system(size: 12, weight: .regular)

    static let audioNotesTopicSelectionTitle = Font.system(size: 36, weight: .heavy)
    static let audioNotesTopicSelectionSubtitle = Font.system(size: 16, weight: .regular)
    static let audioNotesTopicSelectionSectionLabel = Font.system(size: 16, weight: .bold)
    static let audioNotesTopicSelectionRowTitle = Font.system(size: 16, weight: .bold)
    static let audioNotesTopicSelectionRowDetail = Font.system(size: 14, weight: .regular)
    static let audioNotesTopicSelectionRecentTitle = Font.system(size: 14, weight: .bold)
    static let audioNotesTopicSelectionRecentDetail = Font.system(size: 10, weight: .regular)

    static let audioNotesDetailTopBarLabel = Font.system(size: 10, weight: .bold)
    static let audioNotesDetailTopBarTitle = Font.system(size: 14, weight: .semibold)
    static let audioNotesDetailLessonTitle = Font.system(size: 24, weight: .bold)
    static let audioNotesDetailLessonBody = Font.system(size: 14, weight: .regular)
    static let audioNotesDetailTimeLabel = Font.system(size: 11, weight: .bold)
    static let audioNotesDetailSpeedLabel = Font.system(size: 12, weight: .bold)

    static let flashcardsSessionTopBarTitle = Font.system(size: 12, weight: .bold)
    static let flashcardsSessionProgressLabel = Font.system(size: 11, weight: .bold)
    static let flashcardsSessionProgressValue = Font.system(size: 16, weight: .regular)
    static let flashcardsSessionCardEyebrow = Font.system(size: 14, weight: .bold)
    static let flashcardsSessionFrontText = Font.system(size: 42, weight: .heavy)
    static let flashcardsSessionBackText = Font.system(size: 18, weight: .regular)
    static let flashcardsSessionHint = Font.system(size: 12, weight: .regular)
    static let flashcardsSessionRevealButton = Font.system(size: 13, weight: .bold)
    static let flashcardsSessionRemainingBadge = Font.system(size: 11, weight: .bold)
    static let flashcardsSessionActionButton = Font.system(size: 13, weight: .bold)
}
